
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'Article': typeof import("../components/Article.vue")['default']
    'Button': typeof import("../components/Button.vue")['default']
    'CheckboxValue': typeof import("../components/CheckboxValue.vue")['default']
    'InputValue': typeof import("../components/InputValue.vue")['default']
    'Loader': typeof import("../components/Loader.vue")['default']
    'LoginModal': typeof import("../components/LoginModal.vue")['default']
    'Menu': typeof import("../components/Menu.vue")['default']
    'Menubar': typeof import("../components/Menubar.vue")['default']
    'ModalAlert': typeof import("../components/ModalAlert.vue")['default']
    'Result': typeof import("../components/Result.vue")['default']
    'DesktopImageCard': typeof import("../components/desktop/ImageCard.vue")['default']
    'DesktopMenuai': typeof import("../components/desktop/Menuai.vue")['default']
    'DesktopMenuburger': typeof import("../components/desktop/Menuburger.vue")['default']
    'DesktopMenuevent': typeof import("../components/desktop/Menuevent.vue")['default']
    'DesktopMenuhistoryai': typeof import("../components/desktop/Menuhistoryai.vue")['default']
    'DesktopMenunotify': typeof import("../components/desktop/Menunotify.vue")['default']
    'DesktopMenunpake': typeof import("../components/desktop/Menunpake.vue")['default']
    'DesktopMenuprofile': typeof import("../components/desktop/Menuprofile.vue")['default']
    'DesktopMenusecurity': typeof import("../components/desktop/Menusecurity.vue")['default']
    'DesktopResultAi': typeof import("../components/desktop/ResultAi.vue")['default']
    'DesktopResultBox': typeof import("../components/desktop/ResultBox.vue")['default']
    'DesktopResultHoro': typeof import("../components/desktop/ResultHoro.vue")['default']
    'DesktopResultLotto': typeof import("../components/desktop/ResultLotto.vue")['default']
    'DesktopSlidehome': typeof import("../components/desktop/Slidehome.vue")['default']
    'DesktopTarot': typeof import("../components/desktop/Tarot.vue")['default']
    'DesktopAigentorAigen': typeof import("../components/desktop/aigentor/Aigen.vue")['default']
    'DesktopDetailnewNew': typeof import("../components/desktop/detailnew/New.vue")['default']
    'DesktopFooter': typeof import("../components/desktop/footer/Footer.vue")['default']
    'DesktopHeader': typeof import("../components/desktop/header/Header.vue")['default']
    'DesktopHome': typeof import("../components/desktop/home/Home.vue")['default']
    'DesktopLotto': typeof import("../components/desktop/lotto/Lotto.vue")['default']
    'DesktopProfile': typeof import("../components/desktop/profile/Profile.vue")['default']
    'DesktopReward': typeof import("../components/desktop/reward/Reward.vue")['default']
    'DesktopSupers': typeof import("../components/desktop/supers/Supers.vue")['default']
    'MobileImageCard': typeof import("../components/mobile/ImageCard.vue")['default']
    'MobileResultAi': typeof import("../components/mobile/ResultAi.vue")['default']
    'MobileResultBox': typeof import("../components/mobile/ResultBox.vue")['default']
    'MobileResultHoro': typeof import("../components/mobile/ResultHoro.vue")['default']
    'MobileResultLotto': typeof import("../components/mobile/ResultLotto.vue")['default']
    'MobileSlidehome': typeof import("../components/mobile/Slidehome.vue")['default']
    'MobileTarot': typeof import("../components/mobile/Tarot.vue")['default']
    'MobileAigentorAigen': typeof import("../components/mobile/aigentor/Aigen.vue")['default']
    'MobileDetailnewNew': typeof import("../components/mobile/detailnew/New.vue")['default']
    'MobileFooter': typeof import("../components/mobile/footer/Footer.vue")['default']
    'MobileHeader': typeof import("../components/mobile/header/Header.vue")['default']
    'MobileHome': typeof import("../components/mobile/home/Home.vue")['default']
    'MobileLotto': typeof import("../components/mobile/lotto/Lotto.vue")['default']
    'MobileProfile': typeof import("../components/mobile/profile/Profile.vue")['default']
    'MobileReward': typeof import("../components/mobile/reward/Reward.vue")['default']
    'MobileSupers': typeof import("../components/mobile/supers/Supers.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyArticle': typeof import("../components/Article.vue")['default']
    'LazyButton': typeof import("../components/Button.vue")['default']
    'LazyCheckboxValue': typeof import("../components/CheckboxValue.vue")['default']
    'LazyInputValue': typeof import("../components/InputValue.vue")['default']
    'LazyLoader': typeof import("../components/Loader.vue")['default']
    'LazyLoginModal': typeof import("../components/LoginModal.vue")['default']
    'LazyMenu': typeof import("../components/Menu.vue")['default']
    'LazyMenubar': typeof import("../components/Menubar.vue")['default']
    'LazyModalAlert': typeof import("../components/ModalAlert.vue")['default']
    'LazyResult': typeof import("../components/Result.vue")['default']
    'LazyDesktopImageCard': typeof import("../components/desktop/ImageCard.vue")['default']
    'LazyDesktopMenuai': typeof import("../components/desktop/Menuai.vue")['default']
    'LazyDesktopMenuburger': typeof import("../components/desktop/Menuburger.vue")['default']
    'LazyDesktopMenuevent': typeof import("../components/desktop/Menuevent.vue")['default']
    'LazyDesktopMenuhistoryai': typeof import("../components/desktop/Menuhistoryai.vue")['default']
    'LazyDesktopMenunotify': typeof import("../components/desktop/Menunotify.vue")['default']
    'LazyDesktopMenunpake': typeof import("../components/desktop/Menunpake.vue")['default']
    'LazyDesktopMenuprofile': typeof import("../components/desktop/Menuprofile.vue")['default']
    'LazyDesktopMenusecurity': typeof import("../components/desktop/Menusecurity.vue")['default']
    'LazyDesktopResultAi': typeof import("../components/desktop/ResultAi.vue")['default']
    'LazyDesktopResultBox': typeof import("../components/desktop/ResultBox.vue")['default']
    'LazyDesktopResultHoro': typeof import("../components/desktop/ResultHoro.vue")['default']
    'LazyDesktopResultLotto': typeof import("../components/desktop/ResultLotto.vue")['default']
    'LazyDesktopSlidehome': typeof import("../components/desktop/Slidehome.vue")['default']
    'LazyDesktopTarot': typeof import("../components/desktop/Tarot.vue")['default']
    'LazyDesktopAigentorAigen': typeof import("../components/desktop/aigentor/Aigen.vue")['default']
    'LazyDesktopDetailnewNew': typeof import("../components/desktop/detailnew/New.vue")['default']
    'LazyDesktopFooter': typeof import("../components/desktop/footer/Footer.vue")['default']
    'LazyDesktopHeader': typeof import("../components/desktop/header/Header.vue")['default']
    'LazyDesktopHome': typeof import("../components/desktop/home/Home.vue")['default']
    'LazyDesktopLotto': typeof import("../components/desktop/lotto/Lotto.vue")['default']
    'LazyDesktopProfile': typeof import("../components/desktop/profile/Profile.vue")['default']
    'LazyDesktopReward': typeof import("../components/desktop/reward/Reward.vue")['default']
    'LazyDesktopSupers': typeof import("../components/desktop/supers/Supers.vue")['default']
    'LazyMobileImageCard': typeof import("../components/mobile/ImageCard.vue")['default']
    'LazyMobileResultAi': typeof import("../components/mobile/ResultAi.vue")['default']
    'LazyMobileResultBox': typeof import("../components/mobile/ResultBox.vue")['default']
    'LazyMobileResultHoro': typeof import("../components/mobile/ResultHoro.vue")['default']
    'LazyMobileResultLotto': typeof import("../components/mobile/ResultLotto.vue")['default']
    'LazyMobileSlidehome': typeof import("../components/mobile/Slidehome.vue")['default']
    'LazyMobileTarot': typeof import("../components/mobile/Tarot.vue")['default']
    'LazyMobileAigentorAigen': typeof import("../components/mobile/aigentor/Aigen.vue")['default']
    'LazyMobileDetailnewNew': typeof import("../components/mobile/detailnew/New.vue")['default']
    'LazyMobileFooter': typeof import("../components/mobile/footer/Footer.vue")['default']
    'LazyMobileHeader': typeof import("../components/mobile/header/Header.vue")['default']
    'LazyMobileHome': typeof import("../components/mobile/home/Home.vue")['default']
    'LazyMobileLotto': typeof import("../components/mobile/lotto/Lotto.vue")['default']
    'LazyMobileProfile': typeof import("../components/mobile/profile/Profile.vue")['default']
    'LazyMobileReward': typeof import("../components/mobile/reward/Reward.vue")['default']
    'LazyMobileSupers': typeof import("../components/mobile/supers/Supers.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Article: typeof import("../components/Article.vue")['default']
export const Button: typeof import("../components/Button.vue")['default']
export const CheckboxValue: typeof import("../components/CheckboxValue.vue")['default']
export const InputValue: typeof import("../components/InputValue.vue")['default']
export const Loader: typeof import("../components/Loader.vue")['default']
export const LoginModal: typeof import("../components/LoginModal.vue")['default']
export const Menu: typeof import("../components/Menu.vue")['default']
export const Menubar: typeof import("../components/Menubar.vue")['default']
export const ModalAlert: typeof import("../components/ModalAlert.vue")['default']
export const Result: typeof import("../components/Result.vue")['default']
export const DesktopImageCard: typeof import("../components/desktop/ImageCard.vue")['default']
export const DesktopMenuai: typeof import("../components/desktop/Menuai.vue")['default']
export const DesktopMenuburger: typeof import("../components/desktop/Menuburger.vue")['default']
export const DesktopMenuevent: typeof import("../components/desktop/Menuevent.vue")['default']
export const DesktopMenuhistoryai: typeof import("../components/desktop/Menuhistoryai.vue")['default']
export const DesktopMenunotify: typeof import("../components/desktop/Menunotify.vue")['default']
export const DesktopMenunpake: typeof import("../components/desktop/Menunpake.vue")['default']
export const DesktopMenuprofile: typeof import("../components/desktop/Menuprofile.vue")['default']
export const DesktopMenusecurity: typeof import("../components/desktop/Menusecurity.vue")['default']
export const DesktopResultAi: typeof import("../components/desktop/ResultAi.vue")['default']
export const DesktopResultBox: typeof import("../components/desktop/ResultBox.vue")['default']
export const DesktopResultHoro: typeof import("../components/desktop/ResultHoro.vue")['default']
export const DesktopResultLotto: typeof import("../components/desktop/ResultLotto.vue")['default']
export const DesktopSlidehome: typeof import("../components/desktop/Slidehome.vue")['default']
export const DesktopTarot: typeof import("../components/desktop/Tarot.vue")['default']
export const DesktopAigentorAigen: typeof import("../components/desktop/aigentor/Aigen.vue")['default']
export const DesktopDetailnewNew: typeof import("../components/desktop/detailnew/New.vue")['default']
export const DesktopFooter: typeof import("../components/desktop/footer/Footer.vue")['default']
export const DesktopHeader: typeof import("../components/desktop/header/Header.vue")['default']
export const DesktopHome: typeof import("../components/desktop/home/Home.vue")['default']
export const DesktopLotto: typeof import("../components/desktop/lotto/Lotto.vue")['default']
export const DesktopProfile: typeof import("../components/desktop/profile/Profile.vue")['default']
export const DesktopReward: typeof import("../components/desktop/reward/Reward.vue")['default']
export const DesktopSupers: typeof import("../components/desktop/supers/Supers.vue")['default']
export const MobileImageCard: typeof import("../components/mobile/ImageCard.vue")['default']
export const MobileResultAi: typeof import("../components/mobile/ResultAi.vue")['default']
export const MobileResultBox: typeof import("../components/mobile/ResultBox.vue")['default']
export const MobileResultHoro: typeof import("../components/mobile/ResultHoro.vue")['default']
export const MobileResultLotto: typeof import("../components/mobile/ResultLotto.vue")['default']
export const MobileSlidehome: typeof import("../components/mobile/Slidehome.vue")['default']
export const MobileTarot: typeof import("../components/mobile/Tarot.vue")['default']
export const MobileAigentorAigen: typeof import("../components/mobile/aigentor/Aigen.vue")['default']
export const MobileDetailnewNew: typeof import("../components/mobile/detailnew/New.vue")['default']
export const MobileFooter: typeof import("../components/mobile/footer/Footer.vue")['default']
export const MobileHeader: typeof import("../components/mobile/header/Header.vue")['default']
export const MobileHome: typeof import("../components/mobile/home/Home.vue")['default']
export const MobileLotto: typeof import("../components/mobile/lotto/Lotto.vue")['default']
export const MobileProfile: typeof import("../components/mobile/profile/Profile.vue")['default']
export const MobileReward: typeof import("../components/mobile/reward/Reward.vue")['default']
export const MobileSupers: typeof import("../components/mobile/supers/Supers.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyArticle: typeof import("../components/Article.vue")['default']
export const LazyButton: typeof import("../components/Button.vue")['default']
export const LazyCheckboxValue: typeof import("../components/CheckboxValue.vue")['default']
export const LazyInputValue: typeof import("../components/InputValue.vue")['default']
export const LazyLoader: typeof import("../components/Loader.vue")['default']
export const LazyLoginModal: typeof import("../components/LoginModal.vue")['default']
export const LazyMenu: typeof import("../components/Menu.vue")['default']
export const LazyMenubar: typeof import("../components/Menubar.vue")['default']
export const LazyModalAlert: typeof import("../components/ModalAlert.vue")['default']
export const LazyResult: typeof import("../components/Result.vue")['default']
export const LazyDesktopImageCard: typeof import("../components/desktop/ImageCard.vue")['default']
export const LazyDesktopMenuai: typeof import("../components/desktop/Menuai.vue")['default']
export const LazyDesktopMenuburger: typeof import("../components/desktop/Menuburger.vue")['default']
export const LazyDesktopMenuevent: typeof import("../components/desktop/Menuevent.vue")['default']
export const LazyDesktopMenuhistoryai: typeof import("../components/desktop/Menuhistoryai.vue")['default']
export const LazyDesktopMenunotify: typeof import("../components/desktop/Menunotify.vue")['default']
export const LazyDesktopMenunpake: typeof import("../components/desktop/Menunpake.vue")['default']
export const LazyDesktopMenuprofile: typeof import("../components/desktop/Menuprofile.vue")['default']
export const LazyDesktopMenusecurity: typeof import("../components/desktop/Menusecurity.vue")['default']
export const LazyDesktopResultAi: typeof import("../components/desktop/ResultAi.vue")['default']
export const LazyDesktopResultBox: typeof import("../components/desktop/ResultBox.vue")['default']
export const LazyDesktopResultHoro: typeof import("../components/desktop/ResultHoro.vue")['default']
export const LazyDesktopResultLotto: typeof import("../components/desktop/ResultLotto.vue")['default']
export const LazyDesktopSlidehome: typeof import("../components/desktop/Slidehome.vue")['default']
export const LazyDesktopTarot: typeof import("../components/desktop/Tarot.vue")['default']
export const LazyDesktopAigentorAigen: typeof import("../components/desktop/aigentor/Aigen.vue")['default']
export const LazyDesktopDetailnewNew: typeof import("../components/desktop/detailnew/New.vue")['default']
export const LazyDesktopFooter: typeof import("../components/desktop/footer/Footer.vue")['default']
export const LazyDesktopHeader: typeof import("../components/desktop/header/Header.vue")['default']
export const LazyDesktopHome: typeof import("../components/desktop/home/Home.vue")['default']
export const LazyDesktopLotto: typeof import("../components/desktop/lotto/Lotto.vue")['default']
export const LazyDesktopProfile: typeof import("../components/desktop/profile/Profile.vue")['default']
export const LazyDesktopReward: typeof import("../components/desktop/reward/Reward.vue")['default']
export const LazyDesktopSupers: typeof import("../components/desktop/supers/Supers.vue")['default']
export const LazyMobileImageCard: typeof import("../components/mobile/ImageCard.vue")['default']
export const LazyMobileResultAi: typeof import("../components/mobile/ResultAi.vue")['default']
export const LazyMobileResultBox: typeof import("../components/mobile/ResultBox.vue")['default']
export const LazyMobileResultHoro: typeof import("../components/mobile/ResultHoro.vue")['default']
export const LazyMobileResultLotto: typeof import("../components/mobile/ResultLotto.vue")['default']
export const LazyMobileSlidehome: typeof import("../components/mobile/Slidehome.vue")['default']
export const LazyMobileTarot: typeof import("../components/mobile/Tarot.vue")['default']
export const LazyMobileAigentorAigen: typeof import("../components/mobile/aigentor/Aigen.vue")['default']
export const LazyMobileDetailnewNew: typeof import("../components/mobile/detailnew/New.vue")['default']
export const LazyMobileFooter: typeof import("../components/mobile/footer/Footer.vue")['default']
export const LazyMobileHeader: typeof import("../components/mobile/header/Header.vue")['default']
export const LazyMobileHome: typeof import("../components/mobile/home/Home.vue")['default']
export const LazyMobileLotto: typeof import("../components/mobile/lotto/Lotto.vue")['default']
export const LazyMobileProfile: typeof import("../components/mobile/profile/Profile.vue")['default']
export const LazyMobileReward: typeof import("../components/mobile/reward/Reward.vue")['default']
export const LazyMobileSupers: typeof import("../components/mobile/supers/Supers.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
